marriage_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('__debug__/', include('debug_toolbar.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views, api_views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('register/', views.RegistrationUser.as_view(), name='register'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('profile/<int:pk>/', views.UserPublicProfileView.as_view(), name='public_profile'),
    path('profile/delete_photo/', views.DeletePhotoView.as_view(), name='delete_photo'),
    path('proposal/', views.ProposalHTML.as_view(), name='proposal'),
    path('api/proposal/', api_views.ProposalAPI.as_view(), name='proposal-api'),
    path('offers/', views.OffersHTML.as_view(), name='offers-list'),
    path('api/offers/<int:pk>/', api_views.OffersAPI.as_view(), name='offers-api'),
    path('api/divorce/', api_views.DivorceAPI.as_view(), name='divorce-api'),
    path('marriages/', views.MarriagesHTML.as_view(), name='marriages-list'),
    path('api/users/autocomplete/', api_views.UserAutocompleteView.as_view(), name='user-autocomplete'),

]

users/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models


class MarriedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(husband__isnull=False)


class User(AbstractUser):
    class Gender(models.IntegerChoices):
        MAN = 1, 'Мужской'
        WOMAN = 0, 'Женский'

    is_married = models.BooleanField(default=False, verbose_name='Married')
    gender = models.SmallIntegerField(
        choices=Gender.choices,
        default=None
    )
    first_name = models.CharField(max_length=150, blank=False, null=False, verbose_name='Имя')
    last_name = models.CharField(max_length=150, blank=False, null=False, verbose_name='Фамилия')

    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', default=None, blank=True, null=True, verbose_name='Фото')

    objects = UserManager()
    married = MarriedManager()

    REQUIRED_FIELDS = ['email', 'gender', 'first_name', 'last_name']

    @property
    def partner(self):
        if not hasattr(self, '_partner'):
            marriage = self.active_marriage  # Используем уже оптимизированный property
            if marriage:
                self._partner = marriage.wife if marriage.husband == self else marriage.husband
            else:
                self._partner = None
        return self._partner

    @property
    def active_marriage(self):
        if not hasattr(self, '_active_marriage'):
            self._active_marriage = self.husband.filter(status=Marriage.Status.ACTIVE).first() or \
                                    self.wife.filter(status=Marriage.Status.ACTIVE).first()
        return self._active_marriage

    @property
    def has_photo(self):
        if self.photo:
            try:
                return self.photo.url
            except ValueError:
                pass
        return f"{settings.MEDIA_URL}users/default.png"


    def __str__(self):
        return self.username


class Marriage(models.Model):
    class Status(models.IntegerChoices):
        ACTIVE = 1, 'Активный'
        DIVORCED = 0, 'Расторгнут'

    husband = models.ForeignKey('User', on_delete=models.CASCADE, related_name='husband', verbose_name='Муж')
    wife = models.ForeignKey('User', on_delete=models.CASCADE, related_name='wife', verbose_name='Жена')

    status = models.SmallIntegerField(choices=Status.choices, default=Status.ACTIVE,verbose_name='Статус')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['husband', 'status'],
                condition=models.Q(status=1),
                name='unique_active_husband'
            ),
            models.UniqueConstraint(
                fields=['wife', 'status'],
                condition=models.Q(status=1),
                name='unique_active_wife'
            ),
        ]

    def display_partner(self, user):
        if user == self.husband:
            return self.wife.get_full_name() or self.wife.username
        elif user == self.wife:
            return self.husband.get_full_name() or self.husband.username
        return None



    def __str__(self):
        return f'{self.husband} + {self.wife}'

class MarriageProposals(models.Model):
    class Status(models.IntegerChoices):
        COMPLETE = 1, 'Approved'
        CANCELED = 0, 'Canceled'
        WAITING = -1, 'In waiting...'

    sender = models.ForeignKey('User', on_delete=models.CASCADE, related_name='user_sender')
    receiver = models.ForeignKey('User', on_delete=models.CASCADE, null=True, blank=True, related_name='user_receiver')
    receiver_fullname = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name='Unregistered user'
    )

    status = models.SmallIntegerField(choices=Status.choices, default=Status.WAITING,verbose_name='status')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.sender} -> {self.receiver}'

    @property
    def status_display(self) -> str:
        return self.Status(self.status).name

    @property
    def display_receiver(self):
        if self.receiver:
            return self.receiver.get_full_name() or self.receiver.username
        return self.receiver_fullname or "Партнера не найдено"

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import Select

from users.models import User


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={"autofocus": True}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}))

class RegisterUserForm(UserCreationForm):

    username = forms.CharField(label='Логин')
    email = forms.EmailField(
        label='Почта',
        widget=forms.EmailInput(attrs={'placeholder': 'user@example.com'})
    )
    first_name = forms.CharField(max_length=150, required=True, label='Имя')
    last_name = forms.CharField(max_length=150, required=True, label='Фамилия')

    password_attrs = {'autocomplete': 'new-password', 'class': 'form-control'}
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(password_attrs))
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput(password_attrs))

    gender = forms.ChoiceField(
        label='Пол',
        choices=User.Gender.choices,
        widget=Select
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'gender']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("This email has already been registered")
        return email

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}), disabled=True)
    email = forms.CharField(label='Почта',
                            widget=forms.TextInput(attrs={'class': 'form-input'}), disabled=True)
    gender = forms.ChoiceField(choices=User.Gender.choices,label='Пол')

    class Meta:
        model = get_user_model()
        fields = ['photo','username', 'email', 'first_name', 'last_name', 'gender']

class MarriageProposalForm(forms.Form):
    type = forms.CharField(widget=forms.HiddenInput(),
                           required=False)
    receiver_username = forms.CharField(required=False, label="Логин")
    first_name = forms.CharField(required=False, label="Имя")
    last_name = forms.CharField(required=False, label="Фамилия")

    gender_choices = [('', 'Выберите пол')] + list(User.Gender.choices)
    gender = forms.ChoiceField(choices=gender_choices, required=False, label="Пол")

    photo = forms.ImageField(required=False, label='Фото')

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db import models
from django.db.models import Q
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, TemplateView, View, DetailView

from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm, MarriageProposalForm
from users.models import User, Marriage, MarriageProposals


class HomePage(ListView):
    template_name = 'users/index.html'
    extra_context = {
        'title': 'Главная страница'
    }

    def get_queryset(self):
        return User.married.all()


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}
    success_url = 'home'


class RegistrationUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('login')


class UserProfile(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user  # type: User

        context.update({
            'is_married': user.is_married,
            'partner_name': user.partner,
        })

        return context

    def get_success_url(self):
        return reverse_lazy('profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPublicProfileView(DetailView):
    model = get_user_model()
    template_name = 'users/public_profile.html'
    context_object_name = 'profile_user'


class DeletePhotoView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user = request.user
        if user.photo:
            user.photo.delete(save=True)
            return JsonResponse({'success': True})
        return JsonResponse({'success': False, 'error': 'Нет фото'}, status=400)


class ProposalHTML(LoginRequiredMixin, TemplateView):
    template_name = 'users/proposal.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        proposal_type = self.request.GET.get('type', 'registered')
        is_for_registered = proposal_type != 'unregistered'

        free_users = User.objects.filter(~Q(username=self.request.user.username), is_married=False)

        form = MarriageProposalForm(initial={'type': proposal_type})

        context.update({
            'free_users': free_users,
            'is_for_registered': is_for_registered,
            'form': form,
        })

        return context


class OffersHTML(TemplateView):
    template_name = 'users/offers.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Полученные
        incoming = MarriageProposals.objects.filter(
            receiver=self.request.user,
            status=MarriageProposals.Status.WAITING
        )
        # Отправленные заявки
        outgoing = MarriageProposals.objects.filter(
            sender=self.request.user,
            status=MarriageProposals.Status.WAITING
        )

        choice = MarriageProposals.Status

        context.update({
            'offers_incoming': incoming,
            'offers_outgoing': outgoing,
            'request': self.request,
            'choice': choice
        })

        return context


class MarriagesHTML(TemplateView):
    template_name = 'users/marriages-list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        marriages = Marriage.objects.filter(
            models.Q(husband=self.request.user) | models.Q(wife=self.request.user)
        ).select_related('husband', 'wife')

        marriages_data = []
        for marriage in marriages.select_related('husband', 'wife'):
            partner = marriage.wife if marriage.husband == self.request.user else marriage.husband
            marriages_data.append({
                'partner': partner,
                'start_date': marriage.created_at.strftime("%d.%m.%Y"),
                'end_date': marriage.updated_at.strftime(
                    "%d.%m.%Y") if marriage.status != Marriage.Status.ACTIVE else None,
                'is_active': marriage.status == Marriage.Status.ACTIVE,
                'partner_photo': getattr(partner, 'has_photo', '/media/users/default.png')
            })

        marriages_data.sort(key=lambda x: x['start_date'], reverse=True)

        active_marriage = next((m for m in marriages_data if m['is_active']), None)  # Первый активный (или None)
        past_marriages = [m for m in marriages_data if not m['is_active']]  # Список прошедших

        context.update({
            'active_marriage': active_marriage,
            'past_marriages': past_marriages,
            'request': self.request
        })
        return context

users/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
<div class="flex flex-col items-center justify-center min-h-[60vh]">
    <h1 class="text-3xl font-bold text-pink-600 mb-8">Добро пожаловать!</h1>
    <div class="flex flex-col md:flex-row gap-6 mb-8">
        <!-- Две главные кнопки -->
        <a href="{% url 'proposal' %}?type=registered"
           class="bg-gradient-to-r from-pink-400 to-pink-300 text-white text-lg font-semibold px-8 py-4 rounded-xl shadow-lg hover:scale-105 hover:from-pink-500 hover:to-pink-400 transition transform duration-200 text-center">
            Отправить запрос зарегистрированному пользователю
        </a>
        <a href="{% url 'proposal' %}?type=unregistered"
           class="bg-gradient-to-r from-pink-200 to-pink-400 text-pink-900 text-lg font-semibold px-8 py-4 rounded-xl shadow-lg hover:scale-105 hover:from-pink-300 hover:to-pink-500 transition transform duration-200 text-center">
            Отправить запрос незарегистрированному пользователю
        </a>
    </div>
    {% if user.is_authenticated %}
    <div class="flex flex-col md:flex-row gap-4">
        <a href="{% url 'offers-list' %}"
           class="bg-white/80 border border-pink-200 text-pink-600 font-medium px-6 py-3 rounded-lg shadow hover:bg-pink-50 hover:text-pink-800 transition text-center">
            Предложения
        </a>
        <a href="{% url 'marriages-list' %}"
           class="bg-white/80 border border-pink-200 text-pink-600 font-medium px-6 py-3 rounded-lg shadow hover:bg-pink-50 hover:text-pink-800 transition text-center">
            История моих браков
        </a>
    </div>
    {% endif %}
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="max-w-md mx-auto bg-white/90 rounded-2xl shadow-lg p-8 mt-8">
        <h1 class="text-2xl font-bold text-pink-600 mb-6 text-center">{{ title }}</h1>
        <form method="post" class="space-y-5">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}"/>
            {% if form.non_field_errors %}
                <div class="bg-pink-100 border border-pink-300 text-pink-700 rounded p-2 mb-4 text-sm">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            {% for f in form %}
                <div>
                    <label for="{{ f.id_for_label }}" class="block text-pink-700 font-medium mb-1">{{ f.label }}</label>
                    {{ f|add_class:"w-full px-4 py-2 border border-pink-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-pink-300" }}
                    {% if f.errors %}
                        <div class="text-pink-500 text-xs mt-1">{{ f.errors }}</div>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="flex justify-center">
                <button type="submit"
                        class="bg-gradient-to-r from-pink-400 to-pink-300 text-white font-semibold px-8 py-2 rounded-xl shadow hover:scale-105 hover:from-pink-500 hover:to-pink-400 transition transform duration-200">
                    Войти
                </button>
            </div>
        </form>
        <div class="mt-6 text-center">
            <span class="text-gray-600">Нет аккаунта?</span>
            <a href="{% url 'register' %}" class="ml-2 text-pink-600 font-semibold hover:underline">
                Зарегистрироваться
            </a>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="max-w-xl mx-auto bg-white/90 rounded-2xl shadow-lg p-8 mt-8">
        <h1 class="text-2xl font-bold text-pink-600 mb-6 text-center">Профиль</h1>
        <form method="post" enctype="multipart/form-data" class="space-y-5">
            {% csrf_token %}

            <!-- Кастомный блок для фото -->
            <div class="flex flex-col items-center mb-6">
                <div class="w-32 h-32 rounded-full overflow-hidden border-4 border-pink-200 shadow mb-2">
                    <img id="avatarPreview"
                         src="{% if user.photo %}{{ user.photo.url }}{% else %}/media/users/default.png{% endif %}"
                         alt="Аватар"
                         class="object-cover w-full h-full">
                </div>
                <span class="text-pink-500 text-sm mb-2">Измени фото, чтобы выделиться!</span>
                <label class="cursor-pointer bg-pink-100 text-pink-700 px-4 py-2 rounded-lg shadow hover:bg-pink-200 transition mt-2">
                    Изменить фото
                    <input type="file" name="photo" id="id_photo" accept="image/*" class="hidden">
                </label>
                {% if user.photo %}
                    <button type="button" id="deletePhotoBtn"
                            class="mt-2 bg-red-100 text-red-600 px-4 py-2 rounded-lg shadow hover:bg-red-200 transition">
                        Удалить фото
                    </button>
                {% endif %}
                {% if form.photo.errors %}
                    <div class="text-pink-500 text-xs mt-1">{{ form.photo.errors }}</div>
                {% endif %}
            </div>

            <!-- Остальные поля формы -->
            {% for f in form %}
                {% if f.name != "photo" %}
                    <div>
                        <label for="{{ f.id_for_label }}"
                               class="block text-pink-700 font-medium mb-1">{{ f.label }}</label>
                        {{ f|add_class:"w-full px-4 py-2 border border-pink-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-pink-300" }}
                        {% if f.errors %}
                            <div class="text-pink-500 text-xs mt-1">{{ f.errors }}</div>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}

            <div class="mb-4">
                {% if is_married %}
                    <span class="inline-block bg-pink-100 text-pink-700 px-4 py-2 rounded-full font-semibold">
                    💍 В браке с {{ partner_name.get_full_name }}
                </span>
                {% else %}
                    <span class="inline-block bg-gray-100 text-gray-600 px-4 py-2 rounded-full font-semibold">
                    Не состоит в браке
                </span>
                {% endif %}
            </div>

            <div class="flex justify-center">
                <button type="submit"
                        class="bg-gradient-to-r from-pink-400 to-pink-300 text-white font-semibold px-8 py-2 rounded-xl shadow hover:scale-105 hover:from-pink-500 hover:to-pink-400 transition transform duration-200">
                    Сохранить
                </button>
            </div>
        </form>

        {% if is_married %}
            <div class="mt-8 text-center">
                <button id="initiateDivorceBtn"
                        class="bg-pink-100 text-pink-700 font-semibold px-6 py-2 rounded-lg shadow hover:bg-pink-200 transition">
                    Развестись
                </button>
                <div id="result" class="mt-4"></div>
                <div id="confirmationBlock" class="mt-4" style="display: none;">
                    <p class="mb-2">Вы уверены, что хотите развестись с {{ partner_name.get_full_name }}?</p>
                    <button id="confirmDivorceBtn"
                            class="bg-pink-500 text-white px-4 py-2 rounded-lg mr-2 hover:bg-pink-600 transition">Да
                    </button>
                    <button id="cancelDivorceBtn"
                            class="bg-gray-300 text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-400 transition">Нет
                    </button>
                </div>
            </div>
        {% endif %}
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const initiateBtn = document.getElementById('initiateDivorceBtn');
            const confirmationBlock = document.getElementById('confirmationBlock');
            const confirmBtn = document.getElementById('confirmDivorceBtn');
            const cancelBtn = document.getElementById('cancelDivorceBtn');

            // Показываем/скрываем блок подтверждения
            if (initiateBtn && confirmationBlock) {
                initiateBtn.addEventListener('click', function () {
                    initiateBtn.style.display = 'none';
                    confirmationBlock.style.display = 'block';
                });
            }

            // Обработка отмены
            if (cancelBtn && initiateBtn && confirmationBlock) {
                cancelBtn.addEventListener('click', function () {
                    initiateBtn.style.display = 'inline-block';
                    confirmationBlock.style.display = 'none';
                });
            }

            // Обработка подтверждения развода
            if (confirmBtn) {
                confirmBtn.addEventListener('click', async function () {
                    try {
                        const response = await fetch("{% url 'divorce-api' %}", {
                            method: 'PATCH',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',
                                'Content-Type': 'application/json',
                            },
                        });

                        const data = await response.json();

                        if (response.ok) {
                            document.getElementById('result').innerHTML = '<p class="text-green-600">' + (data.detail || "Брак успешно расторгнут") + '</p>';
                            setTimeout(() => {
                                window.location.href = "{% url 'profile' %}";
                            }, 2000);
                        } else {
                            document.getElementById('result').innerHTML = '<p class="text-red-600">Ошибка: ' + (data.detail || "Не удалось расторгнуть брак") + '</p>';
                            if (initiateBtn && confirmationBlock) {
                                initiateBtn.style.display = 'inline-block';
                                confirmationBlock.style.display = 'none';
                            }
                        }
                    } catch (error) {
                        document.getElementById('result').innerHTML = '<p class="text-red-600">Ошибка запроса: ' + error + '</p>';
                        if (initiateBtn && confirmationBlock) {
                            initiateBtn.style.display = 'inline-block';
                            confirmationBlock.style.display = 'none';
                        }
                    }
                });
            }
        });
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const deleteBtn = document.getElementById('deletePhotoBtn');
            if (deleteBtn) {
                deleteBtn.addEventListener('click', async function () {
                    if (!confirm('Вы уверены, что хотите удалить фото?')) return;
                    try {
                        const response = await fetch("{% url 'delete_photo' %}", {
                            method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',
                                'Content-Type': 'application/json',
                            },
                        });
                        if (response.ok) {
                            document.getElementById('avatarPreview').src = '/media/users/default.png';
                            deleteBtn.style.display = 'none';
                        } else {
                            alert('Ошибка при удалении фото');
                        }
                    } catch (error) {
                        alert('Ошибка запроса: ' + error);
                    }
                });
            }
        });
    </script>
    <script>
        document.getElementById('id_photo').addEventListener('change', function (event) {
            const [file] = event.target.files;
            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    document.getElementById('avatarPreview').src = e.target.result;
                }
                reader.readAsDataURL(file);
            }
        });
    </script>
{% endblock %}

users/templates/users/public_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="max-w-md mx-auto bg-white/90 rounded-2xl shadow-lg p-8 mt-8 text-center">
    <div class="flex flex-col items-center mb-6">
        <div class="w-32 h-32 rounded-full overflow-hidden border-4 border-pink-200 shadow mb-2">
            {% if profile_user.photo %}
                <img src="{{ profile_user.photo.url }}" alt="Аватар" class="object-cover w-full h-full">
            {% else %}
                <img src="/media/users/default.png" alt="Аватар" class="object-cover w-full h-full">
            {% endif %}
        </div>
        <h2 class="text-2xl font-bold text-pink-600 mb-2">{{ profile_user.first_name }} {{ profile_user.last_name }}</h2>
        {% if profile_user.gender == 1 %}
            <p class="text-blue-500 mb-2">Пол: {{ profile_user.get_gender_display }}</p>
        {% else %}
            <p class="text-pink-500 mb-2">Пол: {{ profile_user.get_gender_display }}</p>
        {% endif %}
        {% if profile_user.is_married and profile_user.active_marriage %}
            <div class="bg-green-50 border border-green-200 rounded-xl p-4 mt-4 shadow">
                <h3 class="text-lg font-semibold text-green-700 mb-1">В браке</h3>
                <p class="text-green-800">
                    С
                    {% with marriage=profile_user.active_marriage %}
                        {% if marriage.husband == profile_user %}
                            {{ marriage.wife.get_full_name }}
                        {% else %}
                            {{ marriage.husband.get_full_name }}
                        {% endif %}
                        <span class="text-gray-500 text-sm">
                            (с {{ marriage.created_at|date:"d.m.Y" }})
                        </span>
                    {% endwith %}
                </p>
            </div>
        {% else %}
            <span class="inline-block bg-gray-100 text-gray-600 px-4 py-2 rounded-full font-semibold mt-4">
                Не состоит в браке
            </span>
        {% endif %}
        {% if not profile_user.is_married and user.is_authenticated and user != profile_user %}
            <form id="proposal-form" class="mt-6 flex justify-center">
                <input type="hidden" name="receiver_username" value="{{ profile_user.username }}">
                <button type="submit"
                    class="bg-gradient-to-r from-pink-400 to-pink-300 text-white font-semibold px-8 py-2 rounded-xl shadow hover:scale-105 hover:from-pink-500 hover:to-pink-400 transition transform duration-200">
                    Сделать предложение
                </button>
            </form>
            <div id="result" class="mt-4 text-center"></div>
        {% endif %}
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('proposal-form');
    if (form) {
        form.addEventListener('submit', function(event) {
            event.preventDefault();
            const formData = new FormData(form);

            fetch('/api/proposal/', {
                method: 'POST',
                body: formData,
                headers: { 'X-CSRFToken': '{{ csrf_token }}' }
            })
            .then(response => {
                if (!response.ok) {
                    return response.json().then(err => {throw err; });
                }
                return response.json();
            })
            .then(data => {
                document.getElementById('result').innerHTML = '<p class="text-green-600">' + data.message + '</p>';
                form.style.display = 'none';
                setTimeout(() => window.location.reload(), 2000);
            })
            .catch(error => {
                let errorMsg = 'Ошибка: ';
                if (Array.isArray(error)) {
                    // Просто массив ошибок
                    errorMsg += error.join(', ');
                } else if (typeof error === 'object' && error !== null) {
                    // Объект с полями ошибок
                    for (let key in error) {
                        let errs = error[key];
                        if (Array.isArray(errs)) {
                            errs = errs.flat();
                            errorMsg += errs.join(', ') + ' ';
                        } else {
                            errorMsg += errs + ' ';
                        }
                    }
                } else {
                    errorMsg += error;
                }
                document.getElementById('result').innerHTML = '<p class="text-red-600">' + errorMsg.trim() + '</p>';
            });
        });
    }
});
</script>
{% endblock %}